### ISSUE TITLE
Cannot compile with MPLABX IDE v5.15

### ISSUE THREAD

**Issue by romain145** [kcaluwae/dspic33e-bootloader#5]
pps.h, qei32.h, dma.h and ecan.h are missing.
Is this caused by MPLAB dropping PLIB support a few years back?
Could you upload the missing headers or how could I fix this?

```
make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'Z:/git/github/dspic33e-bootloader/dspic_bootloader'
make  -f nbproject/Makefile-default.mk dist/default/production/dspic_bootloader.production.hex
make[2]: Entering directory 'Z:/git/github/dspic33e-bootloader/dspic_bootloader'
"C:\Program Files (x86)\Microchip\xc16\v1.36\bin\xc16-gcc.exe"   bootloader.c  -o build/default/production/bootloader.o  -c -mcpu=33EP256MU806  -MMD -MF "build/default/production/bootloader.o.d"      -mno-eds-warn  -g -omf=elf -DXPRJ_default=default  -no-legacy-libc    -mlarge-code -mlarge-data -O0 -msmart-io=1 -Wall -msfr-warn=off  
"C:\Program Files (x86)\Microchip\xc16\v1.36\bin\xc16-gcc.exe"   canbus.c  -o build/default/production/canbus.o  -c -mcpu=33EP256MU806  -MMD -MF "build/default/production/canbus.o.d"      -mno-eds-warn  -g -omf=elf -DXPRJ_default=default  -no-legacy-libc    -mlarge-code -mlarge-data -O0 -msmart-io=1 -Wall -msfr-warn=off  
bootloader.c:30:17: fatal error: pps.h: No such file or directory
compilation terminated.
make[2]: *** [build/default/production/bootloader.o] Error 255
make[2]: *** Waiting for unfinished jobs....
canbus.c:24:17: fatal error: dma.h: No such file or directory
compilation terminated.
make[2]: *** [build/default/production/canbus.o] Error 255
nbproject/Makefile-default.mk:113: recipe for target 'build/default/production/bootloader.o' failed
nbproject/Makefile-default.mk:120: recipe for target 'build/default/production/canbus.o' failed
make[2]: Leaving directory 'Z:/git/github/dspic33e-bootloader/dspic_bootloader'
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2
nbproject/Makefile-default.mk:90: recipe for target '.build-conf' failed
make[1]: Leaving directory 'Z:/git/github/dspic33e-bootloader/dspic_bootloader'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

BUILD FAILED (exit value 2, total time: 662ms)

```
